# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:

# - script: dotnet restore
  # displayName: 'Packages Restore'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Code Build'
- script: dotnet test DotNet.Test --configuration $(buildConfiguration) --logger trx
  displayName: 'Test Cases'
- script: dotnet publish --configuration $(buildConfiguration)
  displayName: 'Publishing'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip"


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    name: 'drop'

- script: |
    docker build -f ./my-service/Dockerfile -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $pswd
    docker push $(dockerId)/$(imageName)
    displayName: 'ContainerRelease'
  env:
    pswd: $(dockerPassword)
